server:
  port: ${vcap.application.port:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    preferIpAddress: true

